config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#landing'
  get 'music/om', to: 'music#om', as: 'om'
  get 'music/aw', to: 'music#aw', as: 'aw'
  get '/home', to: 'pages#home'
  get 'pages/home', to: 'pages#home'
  get '/music', to: 'pages#music'
  get 'pages/music', to: 'pages#music'
  get '/images', to: 'pages#images'
  get 'pages/images', to: 'pages#images'
  get 'images/photos', to: 'images#photos'
  get '/photos', to: 'images#photos'
  get 'images/graphics', to: 'images#graphics'
  get '/graphics', to: 'images#graphics'
  get 'images/gals-point-guns', to: 'images#gals_point_guns'
  get '/gals-point-guns', to: 'images#gals_point_guns'
  get 'images/rhyparography', to: 'images#rhyparography'
  get 'rhyparography', to: 'images#rhyparography'
  get 'writings', to: 'pages#writings'
  get 'pages/writings', to: 'pages#writings'
  get 'writings/fake-albums', to: 'writings#fake_albums'
  get 'fake-albums', to: 'writings#fake_albums'
  get 'writings/word-salad', to: 'writings#word_salad'
  get 'word-salad', to: 'writings#word_salad'
  get '/fake-albums/butane', to: 'writings#butane'
  get 'fake-albums/porta-xan', to: 'writings#porta_xan'
  get 'fake-albums/pleasant-surprise', to: 'writings#pleasant_surprise'
  get 'fake-albums/cookies', to: 'writings#cookies'
  get '/moodring', to:'moodrings#index'
  resources :videos, only: [:index, :show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/photo.rb
class Photo < ApplicationRecord
end

app/models/photograph.rb
class Photograph < ApplicationRecord
end

app/models/video.rb
class Video < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def default_url_options
    { host: ENV["HOST"] || "localhost:3000" }
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  def photos
    parent
    @photographs = Photograph.where("category IS NULL")
    @photographs
  end

  def graphics
    parent
    @graphics = Photograph.where("category = 'graphic'")
    @graphics
  end

  def gals_point_guns
    parent
  end

  def rhyparography
    parent
  end

  private

  def parent
    @parent = "/images"
    @parent
  end
end

app/controllers/moodrings_controller.rb
class MoodringsController < ApplicationController
  def index
  end
end

app/controllers/music_controller.rb
class MusicController < ApplicationController
  def om
    @parent = "/music"
    @parent
  end

  def aw
    @parent = "/music"
    @parent
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def landing
    @disable_nav = true
  end

  def home
  end

  def music
  end

  def images
  end

  def writings
  end

  def projects
  end

  private

  def disable_nav
    true
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  def index
    @video_essays = Video.where("genre = 'Video Essay'")
    @time_sculptures = Video.where("genre = 'time sculptures'")
    @shitposts = Video.where("genre = 'shitpost'")
    @performance = Video.where("genre = 'performance'")
    @performance
    @video_essays
    @time_sculptures
    @shitposts
  end

  def show
    @parent = "/videos"
    @video = Video.find(params[:id])
    @parent
    @video
  end
end

app/controllers/writings_controller.rb
class WritingsController < ApplicationController
  def fake_albums
    @parent = "/writings"
    @parent
  end

  def word_salad
    @parent = "/writings"
    @parent
  end

  def butane
    fa_parent
  end

  def porta_xan
    fa_parent
  end

  def pleasant_surprise
    fa_parent
  end

  def cookies
    fa_parent
  end

  def fa_parent
    @parent = '/fake-albums'
    @parent
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/images/graphics.html.erb
<div class="gallery">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-md-3 col-lg-3">
      <blockquote class="twitter-tweet" data-conversation="none" data-lang="en"><p lang="und" dir="ltr"> <a href="https://t.co/sZNprkBoZl">pic.twitter.com/sZNprkBoZl</a></p>&mdash; absurdest absurdist🎄 (@Clever_MetaName) <a href="https://twitter.com/Clever_MetaName/status/1078510204688318464?ref_src=twsrc%5Etfw">December 28, 2018</a></blockquote>
      <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
    </div>
    <% @graphics.each do |g| %>
      <div class="col-xs-12 col-sm-6 col-md-3 col-lg-3">
        <div class="thumbnail">
          <a href="<%= g.url %>" target="_blank">
            <%= image_tag "#{g.url}", width: "cover"; %>
              <div class="caption">
                  <%= g.caption %>
              </div>
          </a>
        </div>
      </div>
    <% end %>
  </div>
  <div class="navigation">
    <ul class="list-inline">
      <li><%= link_to "Back", images_path, class: "btn-large" %></li>
      <li><%= link_to "Home", home_path, class: "btn-large" %></li>
    </ul>
  </div>
</div>

app/views/images/photos.html.erb
<div class="gallery">
  <div class="row">
    <% @photographs.each do |p| %>
      <div class="col-xs-12 col-sm-6 col-md-3 col-lg-3">
        <div class="thumbnail">
          <a href="<%= p.url %>" target="_blank">
            <%= image_tag "#{p.url}", width: "cover"; %>
              <div class="caption">
                  <%= "" %>
              </div>
          </a>
        </div>
      </div>
    <% end %>
  </div>
  <%= render 'components/footer-nav' %>
</div>

app/views/images/rhyparography.html.erb
<div class="rhyparography-container">
  <div class="intro">
    <h4>Rhyparography</h4>
    <h5>/ɹɪ.pəˈɹɒ.ɡɹə.fi/</h5>
    <p><em>(arts) The painting or literary depiction of mean or sordid things; especially still-life or genre painting. <br> From Ancient Greek ῥύπος (rhúpos, “filth”) +‎ -graphy.</em></p>
    <p>The aim is to emulate the vivid grotesquery of a <span><em><a href="https://www.google.com/search?q=spongebob+close+up" style="color:#fefcff">Spongebob Close Up</a></em></span> <%= image_tag "link-symbol.svg", width: "10px" %>.<br>These illustrations delight in the perverse, revolting, and hideous because they express the beautiful absurdity and agonizing frustration of physical existence.</p>
    <p></p>
</div>
  <div class="disgust" id="rope-hair">
    <div id="eulogy">
      <p>wipe my ass with my hand and then i'll make ya shake it</p>
      <p>braid my hair into a rope, and run around naked</p>
    </div>
    <%= image_tag "https://i.imgur.com/HCznIb3.jpg", width: "480px" %>
    <%= image_tag "https://i.imgur.com/FokWGF0.jpg", width: "480px" %>
    <%= image_tag "https://i.imgur.com/39XSAdR.png", width: "420px" %>
    <%= image_tag "https://i.imgur.com/sUOQ97d.png", width: "420px" %>
    <%= image_tag "https://i.imgur.com/SDSkvSS.jpg", width: "420px" %>
    <%= image_tag "https://i.imgur.com/CDIxahH.jpg", width: "360px" %>
    <%= image_tag "https://i.imgur.com/uoJ3h7d.jpg", width: "420px" %>
    <%= image_tag "https://i.imgur.com/SmR7ws4.jpg", width: "420px" %>
  </div>
  <div class="disgust">
    <%= image_tag "https://i.imgur.com/aPMrx9e.jpg", width: "720px" %>
    <%= image_tag "https://i.imgur.com/OVwLvkQ.jpg", width: "360px" %>
  </div>
  <div class="disgust" id="sick-comeback">
    <%= image_tag "https://i.imgur.com/LUBnAG1.jpg", width: "840px" %>
  </div>

  <div class="disgust" id="turn-tables">
    <%= image_tag "https://i.imgur.com/n5KxUdh.jpg", width: "480px" %>
  </div>

  <div class="disgust" id="eruptions">
    <%= image_tag "https://i.imgur.com/n66gNXw.jpg", width: "360px" %>
    <%= image_tag "https://i.imgur.com/PxZtiaL.jpg", width: "360px" %>
    <%= image_tag "https://i.imgur.com/j9NwhwS.jpg", width: "360px" %>
  </div>

  <div class="disgust" id="titty-balls">
    <%= image_tag "https://i.imgur.com/M2LsWLz.jpg", width: "480px" %>
  </div>

  <div class="disgust" id="bong-water">
    <%= image_tag "https://i.imgur.com/TgRMf8d.jpg", width: "360px" %>
    <%= image_tag "https://i.imgur.com/YFqghCA.jpg", width: "360px" %>
  </div>

  <div class="disgust" id="davids-feet">
    <%= image_tag "https://i.imgur.com/X7rFFSR.jpg", width: "720px" %>
  </div>
  <div class="disgust" id="good-vibrations">
    <%= image_tag "https://i.imgur.com/8dWJUu4.jpg", width: "480px" %>
  </div>
  <div class="disgust" id="makeover">
    <%= image_tag "https://i.imgur.com/JNhh4iK.jpg", width: "666px" %>
  </div>
  <div class="disgust">
    <%= image_tag "https://i.imgur.com/HT5IAjR.jpg", width: "720px" %>
  </div>
  <div class="disgust" id="white-saviourism">
    <%= image_tag "https://i.imgur.com/JVQIi50.jpg", width: "720px" %>
  </div>
  <div class="disgust" id="beauty-pageant">
    <%= image_tag "https://i.imgur.com/5Yc5jlA.jpg", width: "540px" %>
  </div>
   <div class="disgust" id="world">
    <%= image_tag "https://i.imgur.com/lMKjUCZ.png", width: "360px" %>
  </div>
  <div class="disgust" id="arthur">
    <%= image_tag "https://i.imgur.com/ZTFlpd0.jpg", width: "540px" %>
  </div>
  <div class="disgust" id="most-beautiful">
    <%= image_tag "https://i.imgur.com/TSjdrY6.jpg", width: "720px" %>
  </div>
  <br>
  <br>
  <%= render 'components/footer-nav' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />

    <!-- Twitter Card data -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:title" content="<%= meta_title %>">
    <meta name="twitter:description" content="<%= meta_description %>">
    <meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:image:src" content="<%= meta_image %>">
    <%= csrf_meta_tags %>
    <%= favicon_link_tag(source='ob.svg.png') %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'pages/navbar' unless @disable_nav%>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/moodrings/index.html.erb
<div class="moodring-box">
</div>

app/views/music/aw.html.erb
<div class="aw-container">
  <div class="aw-tracklist row">
    <ul class="">
      <li class="aw-track col-xs-12 col-sm-6 col-md-4 col-lg-3" id="sunset-laughter">
        <iframe width="360" height="240" src="https://www.youtube.com/embed/KSm9hfUteZc" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"allowfullscreen></iframe>
      </li>
      <li class="aw-track col-xs-12 col-sm-6 col-md-4 col-lg-3">
        <iframe width="360" height="240" src="https://www.youtube.com/embed/TK-ILimOw40" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"allowfullscreen></iframe>
      </li>
      <li class="aw-track col-xs-12 col-sm-6 col-md-4 col-lg-3">
        <iframe width="360" height="240" src="https://www.youtube.com/embed/rqP0uH7ZDiE" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
      </li>
      <li class="aw-track col-xs-12 col-sm-6 col-md-4 col-lg-3">
        <iframe width="360" height="240" src="https://www.youtube.com/embed/u3VRXngbKP8" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
      </li>
      <li class="aw-track col-xs-12 col-sm-6 col-md-4 col-lg-3">
        <iframe width="360" height="240" src="https://www.youtube.com/embed/bml4VKaL3dw" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
      </li>
      <li class="aw-track col-xs-12 col-sm-6 col-md-4 col-lg-3">
        <iframe width="360" height="240" src="https://www.youtube.com/embed/lFoepc80lHw" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
      </li>
      <li class="aw-track offset-lg-3">
        <iframe width="360" height="240" src="https://www.youtube.com/embed/dwB49-jqtxU" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
      </li>
    </div>
  </ul>
  <div class="row">
    <iframe width="80%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/491951658&color=%23b0f0d9&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true"></iframe>
  </div>
<div>
  <%= render 'components/footer-nav' %>
</div>

app/views/music/om.html.erb
<div class="om-container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3">
      <iframe style="border: 0; width: 350px; height: 620px;" src="https://bandcamp.com/EmbeddedPlayer/album=1912500894/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=true/transparent=true/" seamless><a href="http://ororomohawk.bandcamp.com/album/lilith">LILITH by Ororo Mohawk</a></iframe>
      <h3><%= link_to "_LILITH LYRICS", "https://genius.com/albums/Ororo-mohawk/Lilith" %></h3>
      <ol>
        <li> <%= link_to "Kiryūin Satsuki", "https://genius.com/Ororo-mohawk-kiryuin-satsuki-lyrics" %> </li>
        <li> <%= link_to "Akasha", "https://genius.com/Ororo-mohawk-akasha-lyrics" %> </li>
        <li> <%= link_to "Medusa", "https://genius.com/Ororo-mohawk-medusa-lyrics" %> </li>
        <li> <%= link_to "Laurie Brown (realeSt wet sKy)", "https://genius.com/Ororo-mohawk-laurie-brown-realest-wet-sky-lyrics" %> </li>
        <li> <%= link_to "Yasser Arafat (Human Centipede)", "https://genius.com/Ororo-mohawk-yasser-arafat-human-centipede-lyrics" %> </li>
        <li> <%= link_to "Ada Lovelace", "https://genius.com/Ororo-mohawk-ada-lovelace-lyrics" %> </li>
        <li> <%= link_to "Kate Moss", "https://genius.com/Ororo-mohawk-kate-moss-lyrics" %> </li>
      </ol>
    </div>
    <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3">
      <iframe style="border: 0; width: 350px; height: 620px;" src="https://bandcamp.com/EmbeddedPlayer/album=4101184538/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=true/transparent=true/" seamless><a href="http://ororomohawk.bandcamp.com/album/hyperbolic-rhyme-chamber">Hyperbolic Rhyme Chamber by Ororo Mohawk</a></iframe>
      <h3><%= link_to "HYPERBOLIC RHYME CHAMBER LYRICS", "https://genius.com/albums/Ororo-mohawk/hyperbolic-rhyme-chamber" %></h3>
      <ol>
        <li> <%= link_to "¥ung Gohan", "https://genius.com/Ororo-mohawk-ung-gohan-lyrics" %> </li>
        <li> <%= link_to "Kusanagi", "https://genius.com/Ororo-mohawk-kusanagi-lyrics" %> </li>
        <li> <%= link_to "Britta Perry", "https://genius.com/Ororo-mohawk-britta-perry-lyrics" %> </li>
      </ol>
    </div>
    <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3">
      <iframe class="col-xs-12 col-sm-6 col-md-4 col-lg-3" style="border: 0; width: 350px; height: 620px;" src="https://bandcamp.com/EmbeddedPlayer/album=3869942056/size=large/bgcol=ffffff/linkcol=0687f5/tracklist=true/transparent=true/" seamless><a href="http://ororomohawk.bandcamp.com/album/wing-zero">wing ZERO by Ororo Mohawk</a></iframe>
    <h3><%= link_to "WING ZERO LYRICS", "https://genius.com/albums/Ororo-mohawk/wing-ZERO" %></h3>
      <ol>
        <li><%= link_to "Heraclitus (ASMR) feat. The Duchess of Winnipeg", "https://genius.com/Ororo-mohawk-heraclitus-asmr-lyrics" %></li>
        <li><%= link_to "Mark Critch", "https://genius.com/Ororo-mohawk-mark-critch-lyrics" %></li>
        <li><%= link_to "$cott $ummers", "https://genius.com/Ororo-mohawk-cott-summers-lyrics" %></li>
      </ol>
    </div>
    <div id="lyrics"></div>
    <%= image_tag "https://i.imgur.com/2IcUL6J.gif", width: "420px" %>
    <br>
    <div class="insta col-lg-12">
      <a href="https://www.instagram.com/ororomohawk/"><i class="fab fa-instagram fa-lg"></i></a>
    </div>
    <br>
    <%= render 'components/footer-nav' %>
  </div>
</div>

app/views/pages/_navbar.html.erb
<div class="topnav" id="myTopnav">
    <a href="/home"><%= image_tag "eat_my_ass.png" %></a>
    <%= link_to "Videos", videos_path %>
    <%= link_to "Music", music_path %>
    <%= link_to "Images", images_path %>
    <%= link_to "Words", writings_path %>
    <a href="javascript:void(0);" class="icon" onclick="myFunction()">&#9776;</a>
</div>

app/views/pages/home.html.erb
<div class="home-container">
    <div id="face">
      <%= image_tag "https://i.imgur.com/QQU3Htt.jpg", class: "face", width: "240px"; %>
      <%= image_tag "https://i.imgur.com/09Jvrme.png", class: "face", id: "magic-realism", width: "240px" %>
    </div>
    <div class="bio">
      <h4>Alexander Mystery Summers Weir</h4>
      <p>
        I am a writer, filmmaker, rapper, full stack Rails developer, photographer, cognitive science enthusiast, and whatever else I can be in order to capture reality and conjure thought.
      </p>
      <p>
        Life is the universe experiencing itself. Through art, language, and media we can maximize the total number of experiences available and thus live life to the fullest possible extent.
      </p>
      <p>Carpe Diem:</p>
      <div class="contact">
        <ul class="links list-inline"">
          <li><a href="mailto:CryptoPynchon@gmail.com"><i class="fa fa-envelope fa-lg" aria-hidden="true"></i></a></li>
          <li><a href="https://www.twitter.com/Clever_Metaname"><i class="fab fa-twitter fa-lg"></i></a></li>
          <li><a href="https://www.instagram.com/twerknowitzki"><i class="fab fa-instagram fa-lg"></i></a></li>
          <li><a href="https://github.com/CryptoPynchon"><i class="fab fa-github fa-lg"></i></a></li>
          <li><a href="https://www.linkedin.com/in/alexander-weir-223103169/"><i class="fab fa-linkedin fa-lg"></i></a></li>
        </ul>
      </div>
    </div>
</div>

app/views/pages/images.html.erb
<div class="image-container">
  <div class="image-row">
    <div class="row">
      <a href="<%= photos_path %>" class="image-card col-xs-12" id="photos-card"><p>Photos</p>
      </a>
      <a href="<%= graphics_path %>" class="image-card col-xs-12" id="graphics-card">
        <p>Graphics</p>
      </a>
    </div>
  </div>
  <div class="image-row">
    <div class="row">
      <!-- easter egg -->
      <!-- <a href="<%= rhyparography_path %>" class="image-card col-xs-12" id="rhyparography-card">
        <p>Rhyparography</p>
      </a> -->
      <a href="<%= gals_point_guns_path %>" class="image-card" col-xs-12 id="gpg-card">
        <p>Gals Point Guns</p>
      </a>
    </div>
  </div>
</div>

app/views/pages/landing.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url(https://res.cloudinary.com/lmn/image/upload/e_sharpen:100/f_auto,fl_lossy,q_auto/v1/gameskinnyc/g/a/x/gax1-8bb0b.jpg);">
  <div class="banner-content">
    <h1>Alex Weird</h1>
    <p>Literally any conceivable experience can be conjured by the mind.</p>
    <p>It is my joy in life to exploit and explore the wondrous possibilities of cognition.</p>
    <%= link_to "Enter", home_path, class: "btn-large"%>
  </div>
</div>

app/views/pages/music.html.erb
<div class="music-container">
  <div class="center">
    <div class="row">
      <a href="<%= aw_path %>" class="card col-xs-12 col-sm-6 col-md-4 col-lg-3" id="aw-card"><p>Alex Weird</p></a>
      <a href="<%= om_path %> " class="card col-xs-12 col-sm-6 col-md-4 col-lg-3" id="om-card"><p>Ororo Mohawk</p></a>
    </div>
  </div>
</div>

app/views/pages/photography.html.erb
<div class="gallery">
  <div class="row">
    <% @photographs.each do |p| %>
      <div class="col-xs-12 col-sm-6 col-md-3 col-lg-3">
        <div class="thumbnail">
          <a href="<%= p.url %>" target="_blank">
            <%= image_tag "#{p.url}", width: "cover"; %>
              <div class="caption">
                  <%= "" %>
              </div>
          </a>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/pages/projects.html.erb
<%= link_to "Fake Albums", fake_albums_path %>

app/views/pages/social.html.erb
Social

app/views/pages/writings.html.erb
<h4>selected ambient words</h4>
<p>Check out my <a href="/videos#video-essays">video essays<%= image_tag "link-symbol.svg", width: "10px" %></a> and <a href="/music/om#lyrics"> lyrics <%= image_tag "link-symbol.svg", width: "10px" %></a> located elsewhere on the site.</p>
<div class="word-container">
  <a href="/fake-albums" class="image-card" id="fa-card"><p>fake albums</p>
  </a>
  <a href="/word-salad" class="image-card" id="ws-card"><p>word salad</p>
  </a>
</div>

app/views/videos/index.html.erb
<div class="content">
  <div class="cards-container">
    <div class="row odd" id="video-essays">
      <h4 style="color:#fefcff">essays 🧚‍♀️</h4>
      <% @video_essays.each do |vid| %>
          <div class="col-xs-12 col-sm-4 col-md-4 col-lg-3">
              <a href="<%= video_path(vid) %>" class="vid-card" style="background-image: url(<%= image_path vid.thumbnail, style: "width: cover;"%>);">
              </a>
            <a href="<%= video_path(vid) %>"><p><%= vid.title %></p></a>
          </div>
      <% end %>
    </div>
    <div class="row even" id="performance">
      <h4 style="color:#fefcff">performances 🌈</h4>
      <% @performance.each do |vid| %>
          <div class="col-xs-12 col-sm-4 col-md-3 col-lg-3">
            <a class="vid-card" href="<%= video_path(vid) %>" style="background-image: url(<%= image_path vid.thumbnail, style: "width: 100%;"%>)">
            </a>
              <a href="<%= video_path(vid) %>"><p><%= vid.title %></p></a>
          </div>
      <% end %>
    </div>
    <div class="row odd" id="time-sculptures">
      <h4 style="color:#fefcff">time sculptures 🌷</h4>
      <% @time_sculptures.each do |vid| %>
          <div class="col-xs-12 col-sm-4 col-md-3 col-lg-3">
              <a href="<%= video_path(vid) %>" class="vid-card" style="background-image: url(<%= image_path vid.thumbnail, style: "width: 100%;"%>);">
              </a>
            <a href="<%= video_path(vid) %>"><p><%= vid.title %></p></a>
          </div>
      <% end %>
    </div>
    <div class="row even" id="shitposts">
      <h4 style="color:#fefcff">shitposts 💯</h4>
      <% @shitposts.each do |vid| %>
          <div class="col-xs-12 col-sm-4 col-md-3 col-lg-3">
            <a class="vid-card" href="<%= video_path(vid) %>" style="background-image: url(<%= image_path vid.thumbnail, style: "width: 100%;"%>)">
            </a>
              <a href="<%= video_path(vid) %>"><p><%= vid.title %></p></a>
          </div>
      <% end %>
    </div>
  </div>
</div>
<div class="conform">
  <script src="https://apis.google.com/js/platform.js"></script>
  <div class="g-ytsubscribe" data-channelid="UCGSSYA9EMC2rcEMuJpiBYNg" data-layout="full" data-theme="dark" data-count="default"></div>
</div>